<?php
$storeId = Mage::app()->getStore()->getStoreId();
$ajax_cart		 		= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_cart', $storeId); 
$image_product_hover 	= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/image_product_hover', $storeId);
$rating_wishlist_compare	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/rating_wishlist_compare', $storeId); 
$quick_view	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_quickview', $storeId);  
$thumb_width =  Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_width', $storeId);
$thumb_height = Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_height', $storeId);
$_productCollection=$this->getProductCollection();
$r = $this->getFrontendHash();
$_helper = $this->helper('catalog/output');
?>
				    <div class="block-products-list-sidebar">
					    <div id="block-products-list-sidebar" class="block-title">
					        <strong><span><?php echo $this->getWidgetTitle();?></span></strong>
					    </div>
<?php $i=0; foreach ($_productCollection as $_product): ?>					    
					    <div class="row block-content f-no-space">
			            	<div class="col-md-left">
								<div class="item-product-image-box"> 
			               <a class="product-image" title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>">
				           		<div class="margin-image"><img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>"></div>              
				           </a>
								</div>
						    </div>
							<div class="col-md-right">
							    <h3 class="product-name">
							    	<a title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
							    </h3>
							   <?php echo $this->getPriceHtml($_product, true) ?>
            <div class="rating-product-box">
			            <?php
	                    $_reviews = Mage::getModel('review/review')->getResourceCollection();              
	                      $_reviews->addStoreFilter( Mage::app()->getStore()->getId() )  
	                                ->addEntityFilter('product', $_product->getId())
	                              ->addStatusFilter( Mage_Review_Model_Review::STATUS_APPROVED )  
	                              ->setDateOrder()  
	                              ->addRateVotes(); 
                    
                            $avg = 0; 
                            $ratings = array(); 
                            if (count($_reviews) > 0){
                            foreach ($_reviews->getItems() as $_review): ?>
                            <?php foreach( $_review->getRatingVotes() as $_vote ): ?>
                                    <?php $ratings[] = $_vote->getPercent();   ?>
                                <?php endforeach; ?>
                            <?php endforeach;   
                            $avg = array_sum($ratings)/count($ratings); 
                            ?> 
                     
                    <div class="rating-box">  
                      <div class="rating" style="width: <?php echo ceil($avg) ; ?>%;"></div>  
                    </div>					
                    <?php }?>
                    </div>
                    
							</div>
					    </div>

<?php endforeach; ?>
					</div>





