
<?php
 $storeId = Mage::app()->getStore()->getStoreId();
 $custom_header					=	Mage::getStoreConfig('themeoptions_general/general_options/custom_header', $storeId);
 $header_get = $_GET['header'];
 if($header_get) {
	 $custom_header = $header_get;
 }else{
 	$custom_header					=	Mage::getStoreConfig('themeoptions_general/general_options/custom_header', $storeId);
 }
?>
<div class="mini-cart">
    <?php $_cartQty = $this->getSummaryCount() ?>
    	<div class="shopping-cart"> 
		<?php  if($custom_header == '') :?>

    		<div class="cart-icon-top"><i class="icon-basket-circled"></i></div>   
			<a class="mini-cart-title" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>">
				<span><?php echo $this->__('Shopping Cart'); ?></span>       
				<span class="cart_circle<?php if($_cartQty): echo " active"; endif;?>">
				<?php if($_cartQty): echo " ( ".$_cartQty." ) item "; endif;?></span>
			</a>
		<?php elseif($custom_header == 'custom-header-1') : ?>
    		
    		<div class="cart-icon-top">
    			<div class="view-shopping-cart"><a class="mini-cart-title" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>"></a></div>
    			<div class="shopping-cart"><?php echo $this->__('Shopping Cart'); ?></div> 
                <div class="amount"><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()); ?> <i class="icon-down-open"></i></div>
    			</div>
    			
    	<?php elseif($custom_header == 'custom-header-2') :?>

    		<div class="cart-icon-top"><i class="icon-basket"></i></div>   
			<a class="mini-cart-title" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>">
				<span><?php echo $this->__('Shopping Cart'); ?></span>       
				<span class="cart_circle<?php if($_cartQty): echo " active"; endif;?>">
				<?php if($_cartQty): echo " ( ".$_cartQty." ) item "; endif;?></span>
			</a> 
    	<?php elseif($custom_header == 'custom-header-3') : ?>
    		
    		<div class="cart-icon-top">
    			<a class="mini-cart-title" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>"></a>
    			<span><?php echo $this->__(''); ?><i class="icon-basket-2"></i></span> 
                
    			</div>   			
		<?php endif;?>
		</div>  
    <?php $_items = $this->getRecentItems(); ?>
    <?php if(count($_items)): ?>
    	<div class="block-content">
    		<div class="block-content-inner">
	            <p class="block-subtitle"><?php echo $this->__('') ?></p>
	            <ol id="cart-sidebar" class="mini-products-list">
	            <?php foreach($_items as $_item): ?>
	                <?php echo $this->getItemHtml($_item) ?>
	            <?php endforeach; ?>
	            </ol>          
	            <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
	            
	            <div class="actions">
	            	<button type="button" title="<?php echo $this->__('View contents of your shopping cart') ?>" class="button btn-inline button-shopcart" onclick="setLocation('<?php echo $this->getUrl('checkout/cart') ?>')"><span><span><?php echo $this->__('View cart') ?></span></span></button>
	            	<button type="button" title="<?php echo $this->__('View contents of your shopping cart') ?>" class="button btn-inline" onclick="setLocation('<?php echo $this->getUrl('checkout/onepage') ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
	            	<?php echo $this->getChildHtml('extra_actions') ?>
	            </div>
			</div>
        </div>
    <?php else: ?>
    	<div class="block-content">
        <div class="block-content-inner">
            	<p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
		</div>
		</div>
    <?php endif ?>
</div>
